// auto generated by c2z
#include <new>
#include "DetourAssert.h"

extern "C" void _1_dtAssertFailSetCustom_(dtAssertFailFunc * assertFailFunc) { ::dtAssertFailSetCustom(assertFailFunc); }
extern "C" dtAssertFailFunc * _1_dtAssertFailGetCustom_() { return ::dtAssertFailGetCustom(); }
