// auto generated by c2z
#include <new>
#include "DetourAlloc.h"

extern "C" void _1_dtAllocSetCustom_(dtAllocFunc * allocFunc, dtFreeFunc * freeFunc) { ::dtAllocSetCustom(allocFunc, freeFunc); }
extern "C" void * _1_dtAlloc_(size_t size, dtAllocHint hint) { return ::dtAlloc(size, hint); }
extern "C" void _1_dtFree_(void * ptr) { ::dtFree(ptr); }
