// auto generated by c2z
#include <new>
#include "DetourStatus.h"

extern "C" const void* _1_DT_FAILURE_ = (void*)& ::DT_FAILURE;
extern "C" const void* _1_DT_SUCCESS_ = (void*)& ::DT_SUCCESS;
extern "C" const void* _1_DT_IN_PROGRESS_ = (void*)& ::DT_IN_PROGRESS;
extern "C" const void* _1_DT_STATUS_DETAIL_MASK_ = (void*)& ::DT_STATUS_DETAIL_MASK;
extern "C" const void* _1_DT_WRONG_MAGIC_ = (void*)& ::DT_WRONG_MAGIC;
extern "C" const void* _1_DT_WRONG_VERSION_ = (void*)& ::DT_WRONG_VERSION;
extern "C" const void* _1_DT_OUT_OF_MEMORY_ = (void*)& ::DT_OUT_OF_MEMORY;
extern "C" const void* _1_DT_INVALID_PARAM_ = (void*)& ::DT_INVALID_PARAM;
extern "C" const void* _1_DT_BUFFER_TOO_SMALL_ = (void*)& ::DT_BUFFER_TOO_SMALL;
extern "C" const void* _1_DT_OUT_OF_NODES_ = (void*)& ::DT_OUT_OF_NODES;
extern "C" const void* _1_DT_PARTIAL_RESULT_ = (void*)& ::DT_PARTIAL_RESULT;
extern "C" const void* _1_DT_ALREADY_OCCUPIED_ = (void*)& ::DT_ALREADY_OCCUPIED;
extern "C" bool _1_dtStatusSucceed_(dtStatus status) { return ::dtStatusSucceed(status); }
extern "C" bool _1_dtStatusFailed_(dtStatus status) { return ::dtStatusFailed(status); }
extern "C" bool _1_dtStatusInProgress_(dtStatus status) { return ::dtStatusInProgress(status); }
extern "C" bool _1_dtStatusDetail_(dtStatus status, unsigned int detail) { return ::dtStatusDetail(status, detail); }
