// auto generated by c2z
const std = @import("std");
//const cpp = @import("cpp");

pub const dtStatus = c_uint;

extern const _1_DT_FAILURE_: *const c_uint;
pub const DT_FAILURE = _1_DT_FAILURE_;

extern const _1_DT_SUCCESS_: *const c_uint;
pub const DT_SUCCESS = _1_DT_SUCCESS_;

extern const _1_DT_IN_PROGRESS_: *const c_uint;
pub const DT_IN_PROGRESS = _1_DT_IN_PROGRESS_;

extern const _1_DT_STATUS_DETAIL_MASK_: *const c_uint;
pub const DT_STATUS_DETAIL_MASK = _1_DT_STATUS_DETAIL_MASK_;

extern const _1_DT_WRONG_MAGIC_: *const c_uint;
pub const DT_WRONG_MAGIC = _1_DT_WRONG_MAGIC_;

extern const _1_DT_WRONG_VERSION_: *const c_uint;
pub const DT_WRONG_VERSION = _1_DT_WRONG_VERSION_;

extern const _1_DT_OUT_OF_MEMORY_: *const c_uint;
pub const DT_OUT_OF_MEMORY = _1_DT_OUT_OF_MEMORY_;

extern const _1_DT_INVALID_PARAM_: *const c_uint;
pub const DT_INVALID_PARAM = _1_DT_INVALID_PARAM_;

extern const _1_DT_BUFFER_TOO_SMALL_: *const c_uint;
pub const DT_BUFFER_TOO_SMALL = _1_DT_BUFFER_TOO_SMALL_;

extern const _1_DT_OUT_OF_NODES_: *const c_uint;
pub const DT_OUT_OF_NODES = _1_DT_OUT_OF_NODES_;

extern const _1_DT_PARTIAL_RESULT_: *const c_uint;
pub const DT_PARTIAL_RESULT = _1_DT_PARTIAL_RESULT_;

extern const _1_DT_ALREADY_OCCUPIED_: *const c_uint;
pub const DT_ALREADY_OCCUPIED = _1_DT_ALREADY_OCCUPIED_;

extern fn _1_dtStatusSucceed_(status: dtStatus) bool;
/// Returns true of status is success.
pub const dtStatusSucceed = _1_dtStatusSucceed_;

extern fn _1_dtStatusFailed_(status: dtStatus) bool;
/// Returns true of status is failure.
pub const dtStatusFailed = _1_dtStatusFailed_;

extern fn _1_dtStatusInProgress_(status: dtStatus) bool;
/// Returns true of status is in progress.
pub const dtStatusInProgress = _1_dtStatusInProgress_;

extern fn _1_dtStatusDetail_(status: dtStatus, detail: c_uint) bool;
/// Returns true if specific detail is set.
pub const dtStatusDetail = _1_dtStatusDetail_;
