// auto generated by c2z
#include <new>
#include "DetourNavMeshBuilder.h"

extern "C" bool _1_dtCreateNavMeshData_(dtNavMeshCreateParams * params, unsigned char ** outData, int * outDataSize) { return ::dtCreateNavMeshData(params, outData, outDataSize); }
extern "C" bool _1_dtNavMeshHeaderSwapEndian_(unsigned char * data, const int dataSize) { return ::dtNavMeshHeaderSwapEndian(data, dataSize); }
extern "C" bool _1_dtNavMeshDataSwapEndian_(unsigned char * data, const int dataSize) { return ::dtNavMeshDataSwapEndian(data, dataSize); }
