// auto generated by c2z
#include <new>
#include "RecastAlloc.h"

extern "C" void _1_rcAllocSetCustom_(rcAllocFunc * allocFunc, rcFreeFunc * freeFunc) { ::rcAllocSetCustom(allocFunc, freeFunc); }
extern "C" void * _1_rcAlloc_(size_t size, rcAllocHint hint) { return ::rcAlloc(size, hint); }
extern "C" void _1_rcFree_(void * ptr) { ::rcFree(ptr); }
extern "C" void _1_rcIntArray_init_(::rcIntArray* self) { new (self) ::rcIntArray(); }
extern "C" void _2_rcIntArray_init_(::rcIntArray* self, int n) { new (self) ::rcIntArray(n); }
