// auto generated by c2z
#include <new>
#include "RecastAssert.h"

extern "C" void _1_rcAssertFailSetCustom_(rcAssertFailFunc * assertFailFunc) { ::rcAssertFailSetCustom(assertFailFunc); }
extern "C" rcAssertFailFunc * _1_rcAssertFailGetCustom_() { return ::rcAssertFailGetCustom(); }
